#!/bin/bash

set -eu
trap exit INT TERM

################################################################################

SOURCE=""
while [ $# -gt 0 ] ; do
key="$1"
case $key in
  --source)  SOURCE="$2";  shift; shift; ;;
  *)                       shift;        ;;
esac
done

################################################################################

if [ -z "${SOURCE}" ] ; then
  (>&2 echo "[error] source package not provided")
  exit 1
fi

################################################################################

lifecycle::rust::lint() {
  local dir="$1"
  if [ -z ${dir} -o ! -d ${dir} ] ; then
    return
  fi

  cd $dir && \
  CARGO_HOME=${dir}/target \
  cargo fmt

  cd $dir && \
  CARGO_HOME=${dir}/target \
  CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=clang-13 \
  CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=clang-13 \
  cargo clippy \
    -- \
    -D warnings \
    -W clippy::pedantic
}

################################################################################

lifecycle::rust::lint \
  ${SOURCE}
