#!/bin/bash

set -eu
trap exit INT TERM

################################################################################

SOURCE=""
while [ $# -gt 0 ] ; do
key="$1"
case $key in
  --source)  SOURCE="$2";  shift; shift; ;;
  *)                       shift;        ;;
esac
done

################################################################################

if [ -z "${SOURCE}" ] ; then
  (>&2 echo "[error] source package not provided")
  exit 1
fi

################################################################################

lifecycle::rust::sync() {
  local dir="$1"
  if [ -z ${dir} -o ! -d ${dir} ] ; then
    return
  fi

  CARGO_HOME=${dir}/target \
  \
  cargo fetch \
    --verbose \
    --manifest-path=${dir}/Cargo.toml
}

################################################################################

lifecycle::rust::sync \
  ${SOURCE}
