#!/bin/bash

set -e
trap exit INT TERM

################################################################################

SOURCE=""
OUTPUT=""
while [ $# -gt 0 ] ; do
key="$1"
case $key in
  --source) SOURCE="$2";  shift; shift; ;;
  --output) OUTPUT="$2";  shift; shift; ;;
  *)                      shift;        ;;
esac
done

################################################################################

if [ -z "${SOURCE}" ] ; then
  (>&2 echo "[error] source package not provided")
  exit 1
fi

if [ -z "${OUTPUT}" ] ; then
  (>&2 echo "[error] output not provided")
  exit 1
fi

################################################################################

lifecycle::rust::test() {
  local dir="$1"
  if [ -z ${dir} -o ! -d ${dir} ] ; then
    return
  fi
  local output="$2"
  local target=$(basename $dir)

  coverage_out=$(mktemp)
  test_out=$(mktemp)

  mkdir -p ${output}

  CARGO_HOME=${dir}/target \
  CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=clang-13 \
  CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=clang-13 \
  \
  cargo test \
    --manifest-path=${dir}/Cargo.toml
}

################################################################################

lifecycle::rust::test \
  ${SOURCE} \
  ${OUTPUT}
