[package]
name = "relay"
version = "0.1.0"
edition = "2018"

[dependencies]
log = { version = "0.4" }
config = { path = "../config" }
metrics = { path = "../metrics" }
zmq = { version = "0.9.2" }
zmq-sys = { version = "0.11.0" }
libc = { version = "0.2.15" }

[build-dependencies]