[package]
name = "metrics"
version = "0.1.0"
edition = "2018"

[dependencies]
log = { version = "0.4" }
config = { path = "../config" }
statsd = { version = "0.13.1" }
systemstat = { version = "0.1.7" }

[build-dependencies]