#!/bin/sh

set -e

case "$1" in

  purge)
		systemctl stop lake.service
		systemctl disable lake.service
		(rm /lib/systemd/system/lake.service || :)
		(rm /lib/systemd/system/lake.service || :)
		(rm /etc/init/lake.conf || :)
    (rm /opt/lake/metrics/metrics.json || :)
		systemctl daemon-reload
		systemctl reset-failed
	;;

	remove)
		systemctl mask lake.service
	;;

  upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
  ;;

  *)
    (>&2 echo "postrm called with unknown argument \`$1'")
    exit 1
  ;;

esac

exit 0
