#!/bin/sh

set -e

case "$1" in

  install|upgrade)
    if [ ! -f "/etc/init/lake.conf" ] ; then
      mkdir -p /etc/init
      touch /etc/init/lake.conf

      echo "LAKE_LOG_LEVEL=INFO" > /etc/init/lake.conf
      echo "LAKE_PORT_PULL=5562" >> /etc/init/lake.conf
      echo "LAKE_PORT_PUB=5561" >> /etc/init/lake.conf
      echo "LAKE_METRICS_REFRESHRATE=1s" >> /etc/init/lake.conf
      echo "LAKE_METRICS_OUTPUT=/opt/lake/metrics/metrics.json" >> /etc/init/lake.conf
    fi
  ;;

  abort-upgrade)
  ;;

  *)
    (>&2 echo "preinst called with unknown argument \`$1'")
    exit 1
  ;;

esac

exit 0
