[package]
name = "main"
version = "0.2.0"
edition = "2021"

[dependencies]
statsd = { version = "0.13.1" }
systemstat = { version = "0.1.7" }
log = "0.4.14"
simple_logger = { version = "1.11.0" }
signal-hook = { version = "0.3.4" }

zmq-sys = { version = "0.11.0" }
libc = { version = "0.2.15" }

[target.'cfg(target_os = "linux")'.dependencies]
procfs = { version = "0.11.0" }
num_cpus = { version = "1.0" }