[package]
name = "main"
version = "0.2.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
zeromq = { version = "0.3.0", default-features = false, features = ["tokio-runtime", "tcp-transport"] }
log = "0.4.14"
statsd = { version = "0.13.1" }
systemstat = { version = "0.1.7" }
