[[constraint]]
  branch = "master"
  name = "github.com/pebbe/zmq4"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/rcrowley/go-metrics"
