#!/bin/bash
# postinst script

set -e

case "$1" in
    configure)
        if [ -f "/etc/lake/params.conf" ] ; then
            echo "Loading params.conf"
            . /etc/lake/params.conf
        else
            (>&2 echo "/etc/lake/params.conf file not found")
            exit 1
        fi
    ;;

    *)
        (>&2 echo "postinst called with unknown argument \ `$1`")
        exit 1
    ;;
esac

exit 0
