#!/bin/bash
# postinst script

set -e

case "$1" in
    configure)
        if [ -f "/openbank/services/lake/params.conf" ] ; then
            echo "Loading params.conf"
            . /openbank/services/lake/params.conf
        else
            echo "/openbank/services/lake/params.conf file not found"
            exit 1
        fi
    ;;

    *)
        echo "postinst called with unknown argument \ `$1`" >&2
        exit 1
    ;;
esac

exit 0
