#!/bin/sh

set -e

delete_service_files() {
  if [ -f "/lib/systemd/system/lake-relay.service" ] ; then
    rm /lib/systemd/system/lake-relay.service
  fi

  if [ -f "/lib/systemd/system/lake.service" ] ; then
    rm /lib/systemd/system/lake.service
  fi

  if [ -f "/lib/systemd/system/lake.path" ] ; then
    rm /lib/systemd/system/lake.path
  fi
}

delete_displace_files() {
  if [ -f "/etc/init/lake.conf" ] ; then
    rm /etc/init/lake.conf
  fi
}

case "$1" in

  purge)
    # userdel openbank || :

    delete_service_files
    delete_displace_files

    (systemctl daemon-reload || :)
    (systemctl reset-failed || :)
  ;;

  remove)
    (systemctl -a -t service --no-legend  | awk '$1 ~ /lake/ { print $1 }' | xargs -I {} systemctl stop {} 2> /dev/null || :)
    (systemctl daemon-reload || :)

    delete_displace_files
  ;;

  upgrade|deconfigure)
    systemctl stop lake 2> /dev/null || :
  ;;

  remove|failed-upgrade|abort-install|abort-upgrade|disappear)
  ;;

  *)
    (>&2 echo "postrm called with unknown argument \`$1'")
    exit 1
  ;;

esac

exit 0
