.nh
.TH "LAKE" "1" "Jul 2020" "Lake" "OpenBank Lake Manual"
.sp
.SH "NAME"
lake \- starts openbank message relay
.SH "SYNOPSIS"
.sp
.nf
\fIlake
.fi
.sp
.SH "DESCRIPTION"
.sp
The lake relay transforms publish messages to pull queue for openbank services.
.sp
.SH "AUTHORS"
.sp
Jan Cajthaml <jan.cajthaml@gmail.com>
.sp
