name: Health Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '*/30 * * * *'

jobs:

  build:
    name: From Scratch Test
    runs-on: ubuntu-latest
    steps:

    - name: Prepare
      uses: raftario/setup-rust-action@v1
      id: go

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dynamic dependencies
      run: |
        wget https://github.com/zeromq/libzmq/releases/download/v4.3.1/zeromq-4.3.1.tar.gz -O /tmp/zeromq.tar.gz
        tar -xzvf /tmp/zeromq.tar.gz -C /tmp && cd /tmp/zeromq-* && mkdir build && cd build
        cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_CURVE=ON .. && make && sudo make install

    - name: Install static dependencies
      run: |
        cd services/lake
        cargo fetch

    - name: Unit Test
      run:  |
        cd services/lake
        cargo test
